version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./data:/app/data
      - ./crm.db:/app/crm.db
    restart: unless-stopped
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./index.html:/usr/share/nginx/html/index.html:ro
      - ./script.js:/usr/share/nginx/html/script.js:ro
      - ./styles.css:/usr/share/nginx/html/styles.css:ro
    depends_on:
      - web
    restart: unless-stopped 